version: '3.8'

services:
  app:
    build: .
    image: ufo-tracker:latest
    container_name: ufo-tracker
    ports:
      - "5000:5000"
    depends_on:
      - db
    environment:
      - MONGO_URI=mongodb://mongo:27017/ufos

  db:
    image: mongo:latest
    ports:
      - "27017:27017"